x = int(input("Give me the first number: "))
y = int(input("Give me the second number: "))
print("Thank you!")
z = int(x/y)
print(f"{x} + {y} = {x + y}")
print(f"{x} - {y} = {x - y}")
print(f"{x} / {y} = {z}")
print(f"{x} * {y} = {x * y}")